/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace BoostProject {
  export type BoostTransactionStruct = {
    id: BigNumberish;
    timestamp: BigNumberish;
    creator: AddressLike;
    executed: boolean;
    description: string;
    approvalsNeeded: BigNumberish;
  };

  export type BoostTransactionStructOutput = [
    id: bigint,
    timestamp: bigint,
    creator: string,
    executed: boolean,
    description: string,
    approvalsNeeded: bigint
  ] & {
    id: bigint;
    timestamp: bigint;
    creator: string;
    executed: boolean;
    description: string;
    approvalsNeeded: bigint;
  };
}

export interface BoostProjectInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvalCount"
      | "approveTransaction"
      | "boostCounter"
      | "createBoostTransaction"
      | "getApprovalCount"
      | "getApprovalStatus"
      | "getBoostCounter"
      | "getSigners"
      | "getTotalTransactions"
      | "getTransaction"
      | "hasApproved"
      | "isSigner"
      | "nextTransactionId"
      | "operator"
      | "requiredApprovals"
      | "signers"
      | "transactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BoostIncremented"
      | "SignerAdded"
      | "TransactionApproved"
      | "TransactionCreated"
      | "TransactionExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvalCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "boostCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createBoostTransaction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovalCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovalStatus",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBoostCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSigners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTransactionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requiredApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approvalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "boostCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBoostTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBoostCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSigners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTransactionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
}

export namespace BoostIncrementedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    newBoostValue: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: bigint,
    newBoostValue: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    transactionId: bigint;
    newBoostValue: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerAddedEvent {
  export type InputTuple = [signer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [signer: string, timestamp: bigint];
  export interface OutputObject {
    signer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionApprovedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    signer: AddressLike,
    timestamp: BigNumberish,
    currentApprovals: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: bigint,
    signer: string,
    timestamp: bigint,
    currentApprovals: bigint
  ];
  export interface OutputObject {
    transactionId: bigint;
    signer: string;
    timestamp: bigint;
    currentApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionCreatedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    creator: AddressLike,
    timestamp: BigNumberish,
    description: string,
    approvalsNeeded: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: bigint,
    creator: string,
    timestamp: bigint,
    description: string,
    approvalsNeeded: bigint
  ];
  export interface OutputObject {
    transactionId: bigint;
    creator: string;
    timestamp: bigint;
    description: string;
    approvalsNeeded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    timestamp: BigNumberish,
    finalApprovals: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: bigint,
    timestamp: bigint,
    finalApprovals: bigint
  ];
  export interface OutputObject {
    transactionId: bigint;
    timestamp: bigint;
    finalApprovals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BoostProject extends BaseContract {
  connect(runner?: ContractRunner | null): BoostProject;
  waitForDeployment(): Promise<this>;

  interface: BoostProjectInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvalCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  approveTransaction: TypedContractMethod<
    [transactionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  boostCounter: TypedContractMethod<[], [bigint], "view">;

  createBoostTransaction: TypedContractMethod<
    [description: string],
    [bigint],
    "nonpayable"
  >;

  getApprovalCount: TypedContractMethod<
    [transactionId: BigNumberish],
    [bigint],
    "view"
  >;

  getApprovalStatus: TypedContractMethod<
    [transactionId: BigNumberish, signer: AddressLike],
    [boolean],
    "view"
  >;

  getBoostCounter: TypedContractMethod<[], [bigint], "view">;

  getSigners: TypedContractMethod<[], [string[]], "view">;

  getTotalTransactions: TypedContractMethod<[], [bigint], "view">;

  getTransaction: TypedContractMethod<
    [transactionId: BigNumberish],
    [BoostProject.BoostTransactionStructOutput],
    "view"
  >;

  hasApproved: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isSigner: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  nextTransactionId: TypedContractMethod<[], [bigint], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  requiredApprovals: TypedContractMethod<[], [bigint], "view">;

  signers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, boolean, string, bigint] & {
        id: bigint;
        timestamp: bigint;
        creator: string;
        executed: boolean;
        description: string;
        approvalsNeeded: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvalCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveTransaction"
  ): TypedContractMethod<[transactionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "boostCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createBoostTransaction"
  ): TypedContractMethod<[description: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getApprovalCount"
  ): TypedContractMethod<[transactionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getApprovalStatus"
  ): TypedContractMethod<
    [transactionId: BigNumberish, signer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBoostCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalTransactions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [transactionId: BigNumberish],
    [BoostProject.BoostTransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSigner"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextTransactionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requiredApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, boolean, string, bigint] & {
        id: bigint;
        timestamp: bigint;
        creator: string;
        executed: boolean;
        description: string;
        approvalsNeeded: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BoostIncremented"
  ): TypedContractEvent<
    BoostIncrementedEvent.InputTuple,
    BoostIncrementedEvent.OutputTuple,
    BoostIncrementedEvent.OutputObject
  >;
  getEvent(
    key: "SignerAdded"
  ): TypedContractEvent<
    SignerAddedEvent.InputTuple,
    SignerAddedEvent.OutputTuple,
    SignerAddedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionApproved"
  ): TypedContractEvent<
    TransactionApprovedEvent.InputTuple,
    TransactionApprovedEvent.OutputTuple,
    TransactionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionCreated"
  ): TypedContractEvent<
    TransactionCreatedEvent.InputTuple,
    TransactionCreatedEvent.OutputTuple,
    TransactionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;

  filters: {
    "BoostIncremented(uint256,uint256,uint256)": TypedContractEvent<
      BoostIncrementedEvent.InputTuple,
      BoostIncrementedEvent.OutputTuple,
      BoostIncrementedEvent.OutputObject
    >;
    BoostIncremented: TypedContractEvent<
      BoostIncrementedEvent.InputTuple,
      BoostIncrementedEvent.OutputTuple,
      BoostIncrementedEvent.OutputObject
    >;

    "SignerAdded(address,uint256)": TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;
    SignerAdded: TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;

    "TransactionApproved(uint256,address,uint256,uint256)": TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;
    TransactionApproved: TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;

    "TransactionCreated(uint256,address,uint256,string,uint256)": TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;
    TransactionCreated: TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;

    "TransactionExecuted(uint256,uint256,uint256)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
  };
}
