/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace BoostProject {
  export type BoostTransactionStruct = {
    id: BigNumberish;
    timestamp: BigNumberish;
    creator: AddressLike;
    executed: boolean;
    cancelled: boolean;
    description: string;
    approvalsNeeded: BigNumberish;
    txType: BigNumberish;
    targetToken: AddressLike;
    amount: BigNumberish;
    recipient: AddressLike;
    expirationTime: BigNumberish;
  };

  export type BoostTransactionStructOutput = [
    id: bigint,
    timestamp: bigint,
    creator: string,
    executed: boolean,
    cancelled: boolean,
    description: string,
    approvalsNeeded: bigint,
    txType: bigint,
    targetToken: string,
    amount: bigint,
    recipient: string,
    expirationTime: bigint
  ] & {
    id: bigint;
    timestamp: bigint;
    creator: string;
    executed: boolean;
    cancelled: boolean;
    description: string;
    approvalsNeeded: bigint;
    txType: bigint;
    targetToken: string;
    amount: bigint;
    recipient: string;
    expirationTime: bigint;
  };
}

export interface BoostProjectInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approvalCount"
      | "approvalRewardPoints"
      | "approveTransaction"
      | "boostCounter"
      | "cancelTransaction"
      | "createBoostTransaction"
      | "createTransaction"
      | "getBoostCounter"
      | "getSignerAction"
      | "getSignerStats"
      | "getSigners"
      | "getTotalTransactions"
      | "getTransaction"
      | "getTransactionApprovers"
      | "getTransactionRejectors"
      | "getTransactionVotes"
      | "isSigner"
      | "isTransactionActive"
      | "nextTransactionId"
      | "operator"
      | "rejectTransaction"
      | "rejectionCount"
      | "rejectionRewardPoints"
      | "requiredApprovals"
      | "signerActions"
      | "signerApprovals"
      | "signerPoints"
      | "signerRejections"
      | "signers"
      | "transactions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BoostIncremented"
      | "RewardPointsEarned"
      | "SignerAdded"
      | "TransactionApproved"
      | "TransactionCancelled"
      | "TransactionCreated"
      | "TransactionExecuted"
      | "TransactionRejected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approvalCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvalRewardPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "boostCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTransaction",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createBoostTransaction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTransaction",
    values: [
      string,
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBoostCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSignerAction",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSigners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionApprovers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionRejectors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTransactionActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTransactionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rejectTransaction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectionCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectionRewardPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signerActions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerApprovals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerRejections",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transactions",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approvalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvalRewardPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "boostCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBoostTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBoostCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignerAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSigners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionApprovers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionRejectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTransactionActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTransactionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectionRewardPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerRejections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactions",
    data: BytesLike
  ): Result;
}

export namespace BoostIncrementedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    newBoostValue: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: bigint,
    newBoostValue: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    transactionId: bigint;
    newBoostValue: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardPointsEarnedEvent {
  export type InputTuple = [
    signer: AddressLike,
    transactionId: BigNumberish,
    approved: boolean,
    points: BigNumberish,
    totalPoints: BigNumberish
  ];
  export type OutputTuple = [
    signer: string,
    transactionId: bigint,
    approved: boolean,
    points: bigint,
    totalPoints: bigint
  ];
  export interface OutputObject {
    signer: string;
    transactionId: bigint;
    approved: boolean;
    points: bigint;
    totalPoints: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerAddedEvent {
  export type InputTuple = [signer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [signer: string, timestamp: bigint];
  export interface OutputObject {
    signer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionApprovedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    signer: AddressLike,
    timestamp: BigNumberish,
    currentApprovals: BigNumberish,
    pointsEarned: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: bigint,
    signer: string,
    timestamp: bigint,
    currentApprovals: bigint,
    pointsEarned: bigint
  ];
  export interface OutputObject {
    transactionId: bigint;
    signer: string;
    timestamp: bigint;
    currentApprovals: bigint;
    pointsEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionCancelledEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    timestamp: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    transactionId: bigint,
    timestamp: bigint,
    reason: string
  ];
  export interface OutputObject {
    transactionId: bigint;
    timestamp: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionCreatedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    creator: AddressLike,
    timestamp: BigNumberish,
    description: string,
    txType: BigNumberish,
    approvalsNeeded: BigNumberish,
    targetToken: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: bigint,
    creator: string,
    timestamp: bigint,
    description: string,
    txType: bigint,
    approvalsNeeded: bigint,
    targetToken: string,
    amount: bigint
  ];
  export interface OutputObject {
    transactionId: bigint;
    creator: string;
    timestamp: bigint;
    description: string;
    txType: bigint;
    approvalsNeeded: bigint;
    targetToken: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    timestamp: BigNumberish,
    finalApprovals: BigNumberish,
    approvers: AddressLike[]
  ];
  export type OutputTuple = [
    transactionId: bigint,
    timestamp: bigint,
    finalApprovals: bigint,
    approvers: string[]
  ];
  export interface OutputObject {
    transactionId: bigint;
    timestamp: bigint;
    finalApprovals: bigint;
    approvers: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionRejectedEvent {
  export type InputTuple = [
    transactionId: BigNumberish,
    signer: AddressLike,
    timestamp: BigNumberish,
    currentRejections: BigNumberish,
    pointsEarned: BigNumberish
  ];
  export type OutputTuple = [
    transactionId: bigint,
    signer: string,
    timestamp: bigint,
    currentRejections: bigint,
    pointsEarned: bigint
  ];
  export interface OutputObject {
    transactionId: bigint;
    signer: string;
    timestamp: bigint;
    currentRejections: bigint;
    pointsEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BoostProject extends BaseContract {
  connect(runner?: ContractRunner | null): BoostProject;
  waitForDeployment(): Promise<this>;

  interface: BoostProjectInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approvalCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  approvalRewardPoints: TypedContractMethod<[], [bigint], "view">;

  approveTransaction: TypedContractMethod<
    [transactionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  boostCounter: TypedContractMethod<[], [bigint], "view">;

  cancelTransaction: TypedContractMethod<
    [transactionId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  createBoostTransaction: TypedContractMethod<
    [description: string],
    [bigint],
    "nonpayable"
  >;

  createTransaction: TypedContractMethod<
    [
      description: string,
      txType: BigNumberish,
      targetToken: AddressLike,
      amount: BigNumberish,
      recipient: AddressLike,
      expirationDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getBoostCounter: TypedContractMethod<[], [bigint], "view">;

  getSignerAction: TypedContractMethod<
    [transactionId: BigNumberish, signer: AddressLike],
    [bigint],
    "view"
  >;

  getSignerStats: TypedContractMethod<
    [signer: AddressLike],
    [
      [bigint, bigint, bigint] & {
        points: bigint;
        approvals: bigint;
        rejections: bigint;
      }
    ],
    "view"
  >;

  getSigners: TypedContractMethod<[], [string[]], "view">;

  getTotalTransactions: TypedContractMethod<[], [bigint], "view">;

  getTransaction: TypedContractMethod<
    [transactionId: BigNumberish],
    [BoostProject.BoostTransactionStructOutput],
    "view"
  >;

  getTransactionApprovers: TypedContractMethod<
    [transactionId: BigNumberish],
    [string[]],
    "view"
  >;

  getTransactionRejectors: TypedContractMethod<
    [transactionId: BigNumberish],
    [string[]],
    "view"
  >;

  getTransactionVotes: TypedContractMethod<
    [transactionId: BigNumberish],
    [[bigint, bigint] & { approvals: bigint; rejections: bigint }],
    "view"
  >;

  isSigner: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isTransactionActive: TypedContractMethod<
    [transactionId: BigNumberish],
    [boolean],
    "view"
  >;

  nextTransactionId: TypedContractMethod<[], [bigint], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  rejectTransaction: TypedContractMethod<
    [transactionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectionCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  rejectionRewardPoints: TypedContractMethod<[], [bigint], "view">;

  requiredApprovals: TypedContractMethod<[], [bigint], "view">;

  signerActions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  signerApprovals: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  signerPoints: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  signerRejections: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  signers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  transactions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        string,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        timestamp: bigint;
        creator: string;
        executed: boolean;
        cancelled: boolean;
        description: string;
        approvalsNeeded: bigint;
        txType: bigint;
        targetToken: string;
        amount: bigint;
        recipient: string;
        expirationTime: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approvalCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "approvalRewardPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveTransaction"
  ): TypedContractMethod<[transactionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "boostCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelTransaction"
  ): TypedContractMethod<
    [transactionId: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createBoostTransaction"
  ): TypedContractMethod<[description: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "createTransaction"
  ): TypedContractMethod<
    [
      description: string,
      txType: BigNumberish,
      targetToken: AddressLike,
      amount: BigNumberish,
      recipient: AddressLike,
      expirationDuration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBoostCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSignerAction"
  ): TypedContractMethod<
    [transactionId: BigNumberish, signer: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSignerStats"
  ): TypedContractMethod<
    [signer: AddressLike],
    [
      [bigint, bigint, bigint] & {
        points: bigint;
        approvals: bigint;
        rejections: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTotalTransactions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransaction"
  ): TypedContractMethod<
    [transactionId: BigNumberish],
    [BoostProject.BoostTransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransactionApprovers"
  ): TypedContractMethod<[transactionId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTransactionRejectors"
  ): TypedContractMethod<[transactionId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTransactionVotes"
  ): TypedContractMethod<
    [transactionId: BigNumberish],
    [[bigint, bigint] & { approvals: bigint; rejections: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSigner"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTransactionActive"
  ): TypedContractMethod<[transactionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextTransactionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rejectTransaction"
  ): TypedContractMethod<[transactionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rejectionCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "rejectionRewardPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requiredApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "signerActions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "signerApprovals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "signerPoints"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "signerRejections"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "transactions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        boolean,
        boolean,
        string,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        timestamp: bigint;
        creator: string;
        executed: boolean;
        cancelled: boolean;
        description: string;
        approvalsNeeded: bigint;
        txType: bigint;
        targetToken: string;
        amount: bigint;
        recipient: string;
        expirationTime: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BoostIncremented"
  ): TypedContractEvent<
    BoostIncrementedEvent.InputTuple,
    BoostIncrementedEvent.OutputTuple,
    BoostIncrementedEvent.OutputObject
  >;
  getEvent(
    key: "RewardPointsEarned"
  ): TypedContractEvent<
    RewardPointsEarnedEvent.InputTuple,
    RewardPointsEarnedEvent.OutputTuple,
    RewardPointsEarnedEvent.OutputObject
  >;
  getEvent(
    key: "SignerAdded"
  ): TypedContractEvent<
    SignerAddedEvent.InputTuple,
    SignerAddedEvent.OutputTuple,
    SignerAddedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionApproved"
  ): TypedContractEvent<
    TransactionApprovedEvent.InputTuple,
    TransactionApprovedEvent.OutputTuple,
    TransactionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionCancelled"
  ): TypedContractEvent<
    TransactionCancelledEvent.InputTuple,
    TransactionCancelledEvent.OutputTuple,
    TransactionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TransactionCreated"
  ): TypedContractEvent<
    TransactionCreatedEvent.InputTuple,
    TransactionCreatedEvent.OutputTuple,
    TransactionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionRejected"
  ): TypedContractEvent<
    TransactionRejectedEvent.InputTuple,
    TransactionRejectedEvent.OutputTuple,
    TransactionRejectedEvent.OutputObject
  >;

  filters: {
    "BoostIncremented(uint256,uint256,uint256)": TypedContractEvent<
      BoostIncrementedEvent.InputTuple,
      BoostIncrementedEvent.OutputTuple,
      BoostIncrementedEvent.OutputObject
    >;
    BoostIncremented: TypedContractEvent<
      BoostIncrementedEvent.InputTuple,
      BoostIncrementedEvent.OutputTuple,
      BoostIncrementedEvent.OutputObject
    >;

    "RewardPointsEarned(address,uint256,bool,uint256,uint256)": TypedContractEvent<
      RewardPointsEarnedEvent.InputTuple,
      RewardPointsEarnedEvent.OutputTuple,
      RewardPointsEarnedEvent.OutputObject
    >;
    RewardPointsEarned: TypedContractEvent<
      RewardPointsEarnedEvent.InputTuple,
      RewardPointsEarnedEvent.OutputTuple,
      RewardPointsEarnedEvent.OutputObject
    >;

    "SignerAdded(address,uint256)": TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;
    SignerAdded: TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;

    "TransactionApproved(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;
    TransactionApproved: TypedContractEvent<
      TransactionApprovedEvent.InputTuple,
      TransactionApprovedEvent.OutputTuple,
      TransactionApprovedEvent.OutputObject
    >;

    "TransactionCancelled(uint256,uint256,string)": TypedContractEvent<
      TransactionCancelledEvent.InputTuple,
      TransactionCancelledEvent.OutputTuple,
      TransactionCancelledEvent.OutputObject
    >;
    TransactionCancelled: TypedContractEvent<
      TransactionCancelledEvent.InputTuple,
      TransactionCancelledEvent.OutputTuple,
      TransactionCancelledEvent.OutputObject
    >;

    "TransactionCreated(uint256,address,uint256,string,uint8,uint256,address,uint256)": TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;
    TransactionCreated: TypedContractEvent<
      TransactionCreatedEvent.InputTuple,
      TransactionCreatedEvent.OutputTuple,
      TransactionCreatedEvent.OutputObject
    >;

    "TransactionExecuted(uint256,uint256,uint256,address[])": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;

    "TransactionRejected(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      TransactionRejectedEvent.InputTuple,
      TransactionRejectedEvent.OutputTuple,
      TransactionRejectedEvent.OutputObject
    >;
    TransactionRejected: TypedContractEvent<
      TransactionRejectedEvent.InputTuple,
      TransactionRejectedEvent.OutputTuple,
      TransactionRejectedEvent.OutputObject
    >;
  };
}
